---
all:
  hosts:
    # Device "foo" with the following features:
    # - Bluetooth PAN with custom CIDR and one (pre-)trusted device
    # - Ethernet over USB
    foo.local:
      bt_pan:
        cidr: 10.11.10.10/29
        devices: { mac: 00:11:22:33:44:55, pin: '*', trusted: true }
        options:
          # Class syntax, see https://www.ampedrftech.com/datasheets/cod_definition.pdf
          # 0x0104: Computer, 0x0108: Server, 0x020c: Smartphone, 0x0300: LAN / Access point
          - { option: Class, value: "0x0108" }
          - { option: DiscoverableTimeout, value: "0" } # unit: seconds, 0 = always discoverable, default: 180
      usb_gadget:
        ethernet:

    # Device "bar" with custom model and the following features:
    # - Ethernet over USB with custom CIDR
    # - USB Serial Port
    # - custom USB Mass Storage
    bar.local:
      device_info: { model: MacPro7,1@ECOLOR=226,226,224 }
      usb_gadget:
        ethernet: { cidr: 10.10.20.20/29 }
        serial:
        mass_storage: |
          #!/bin/bash

          # create disk image
          if [ ! -f /data/hdd.img ]; then
            mkdir -p /data
            fallocate -l 1GB /data/hdd.img
            mkfs.exfat -v -L 'RaspiDrive' -f /data/hdd.img
          fi

          # create mass storage gadget, see kernel.org/doc/html/latest/usb/gadget-testing.html#mass-storage-function
          echo 1 >stall
          echo /data/hdd.img                  > lun.0/file
          echo 'SanDisk Cruzer Edge     1.20' > lun.0/inquiry_string
          echo 1                              > lun.0/removable
