---
all:
  hosts:
    # Device "foo" with the following features:
    # - USB over Ethernet
    foo:
      usb_gadget:
        ethernet:

    # Device "bar" with custom model and the following features:
    # - customized USB over Ethernet
    # - USB Mass Storage
    # - USB Serial Port
    bar:
      device_info: { model: MacPro7,1@ECOLOR=226,226,224 }
      usb_gadget:
        ethernet: { cidr: 10.10.20.10/29 }
        mass_storage:
        serial:
