---
- name: check samba password for {{ item }}
  shell: "command -v pdbedit >/dev/null && sudo pdbedit --list --user {{ item }}"
  register: pbedit_list_result
  become: true
  failed_when: false

- name: print samba password check for {{ item }}
  debug:
    msg: "Samba password for {{ item }} already set."
  when: pbedit_list_result.rc == 0

- name: request samba password for {{ item }}
  pause:
    echo: false
    prompt: "Enter a Samba password for {{ item }}. Leave empty to skip."
  register: smb_password
  no_log: true
  when: pbedit_list_result.rc != 0

- name: set fact samba password for {{ item }}
  when: pbedit_list_result.rc != 0 and smb_password is defined and not smb_password.failed and smb_password.user_input
  set_fact:
    smb_passwords: "{{ smb_passwords | default({}) | combine({item: smb_password.user_input | b64encode}) }}"
