---
- name: set samba password for {{ item.key }}
  block:
    - name: invoke smbpasswd
      shell: >
        for i in {1..2}; do
          printf %s '{{ item.value }}' | base64 --decode
          printf '\n'
        done | smbpasswd -a {{ item.key }}
      args:
        executable: /bin/bash
      register: smb_password_result
      changed_when: "'New SMB password' in smb_password_result.stdout"
      failed_when: false
      no_log: true
      become: yes

    - name: log smbpasswd failure
      debug:
        msg: "Failed to set samba password for {{ item.key }}: {{ smb_password_result.stderr }}"
      failed_when: true
      when: smb_password_result.rc != 0
