---
- name: create package directory
  ansible.builtin.file:
    path: "{{ package_dir }}"
    state: directory
  become: true

- name: copy files
  ansible.posix.synchronize:
    src: files/
    dest: "{{ package_dir }}/"
  become: true

- name: make pihero executable
  file:
    dest: "{{ package_dir }}/bin/pihero"
    mode: "0755"
  become: true

- name: symlink pihero
  ansible.builtin.file:
    src: "{{ package_dir }}/bin/pihero"
    dest: /usr/local/bin/pihero
    state: link
  become: true

- name: remove outdated hero artifacts
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/profile.d/pihero_path.sh
