---
- hosts: "{{ inventory if inventory is defined else 'all' }}"
  gather_facts: false
  max_fail_percentage: 0

  pre_tasks:
    - name: ensure the group_members fact is set
      import_tasks: tasks/ensure-group_members-fact.yml

    - name: get samba passwords
      include_tasks: roles/smb_shares/tasks/get-samba-password.yml
      loop: "{{ group_members['users'] | default([]) }}"

    - name: update apt packages and allow release info changes
      import_tasks: tasks/apt-update.yml

  roles:
    # configures Kernel HDMI settings
    - role: hdmi
      tags: [ hdmi ]
    # installs Gum—A tool for glamorous shell scripts
    - role: bkahlert.gum
      become: true
      tags: [ gum ]
    # installs the CLI component
    - role: pihero
      tags: [ pihero-cli ]
    # installs the splash component
    - role: splash
      tags: [ splash ]
    # configures device info
    - role: device_info
      tags: [ device-info ]
    # configures Samba shares
    - role: smb_shares
      tags: [ smb ]
    # configures USB gadget
    - role: usb_gadget
      tags: [ gadget ]
    # configures Bluetooth PAN
    - role: bt_pan
      tags: [ pan ]
