---
- hosts: "{{ inventory if inventory is defined else 'all' }}"
  gather_facts: false
  max_fail_percentage: 0

  pre_tasks:
    - name: ensure the group_members fact is set
      import_tasks: tasks/ensure-group_members-fact.yml

    - name: get samba passwords
      include_tasks: roles/smb_shares/tasks/get-samba-password.yml
      loop: "{{ group_members['users'] | default([]) }}"

    - name: update apt packages and allow release info changes
      import_tasks: tasks/apt-update.yml

  roles:
    - { role: bkahlert.gum, become: true }
    - { role: pihero }
    - { role: pihero_splash }
    - { role: device_info }
    - { role: smb_shares }
    - { role: usb_gadget }
    - { role: bt_pan }
