---
- name: silence boot
  import_tasks: silent-boot.yml

- name: copy files
  ansible.builtin.copy:
    src: files/
    dest: "{{ package_dir }}/"
    force: true
  become: true

# themes are located at /usr/share/plymouth/themes
# for custom themes, https://github.com/HerbFargus/plymouth-themes seems to be a good starting point
- name: install plymouth and plymouth-themes
  become: true
  ansible.builtin.apt:
    name: [ plymouth, plymouth-themes ]
    state: present

- name: set plymouth theme
  ansible.builtin.shell: plymouth-set-default-theme --rebuild-initrd {{ splash.theme | default('spinner') }}
  become: true

- name: enable splash screen
  become: true
  kernel_parameters:
    option: splash
    before: rootwait
    state: present

- name: enable plymouth
  become: true
  kernel_parameters:
    option: plymouth.enable
    value: '1'
    after: splash

- name: enable plymouth debug logs to /var/log/plymouth-debug.log
  become: true
  kernel_parameters:
    option: plymouth.debug
    after: plymouth.enable
    state: absent

- name: stop plymouth from displaying anything on the serial console
  become: true
  kernel_parameters:
    option: plymouth.ignore-serial-consoles
    after: plymouth.enable
