---
- name: silence boot
  import_tasks: silent-boot.yml

- name: copy bash files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ package_dir }}/{{ item | basename }}"
    force: true
  with_fileglob:
    - files/*.bash

# themes are located at /usr/share/plymouth/themes
# for custom themes, https://github.com/HerbFargus/plymouth-themes seems to be a good starting point
- name: install plymouth and plymouth-themes
  become: true
  ansible.builtin.apt:
    name: [ plymouth, plymouth-themes ]
    state: present

- name: copy themes
  become: true
  ansible.builtin.copy:
    src: "files/themes/"
    dest: "{{ plymouth_themes_dir }}/"
    force: true

- name: set plymouth theme
  ansible.builtin.shell: plymouth-set-default-theme --rebuild-initrd pihero
  become: true

- name: enable splash screen
  become: true
  kernel_parameters:
    option: splash
    before: rootwait
    state: present

- name: enable plymouth
  become: true
  kernel_parameters:
    option: plymouth.enable
    value: '1'
    after: splash

- name: enable plymouth debug logs to /var/log/plymouth-debug.log
  become: true
  kernel_parameters:
    option: plymouth.debug
    after: plymouth.enable
    state: absent

- name: stop plymouth from displaying anything on the serial console
  become: true
  kernel_parameters:
    option: plymouth.ignore-serial-consoles
    after: plymouth.enable
