---
- name: request samba password for {{ item }}
  pause:
    echo: false
    prompt: "Enter a Samba password for {{ item }}. Leave empty to skip."
  register: smb_password
  no_log: true

- name: set fact samba password for {{ item }}
  when: not smb_password.failed and smb_password.user_input
  set_fact:
    smb_passwords: "{{ smb_passwords | default({}) | combine({item: smb_password.user_input | b64encode}) }}"
