---
- name: ensure /etc/apt/keyrings directory
  ansible.builtin.file:
    path: "{{ apt_keyrings_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: download and dearmor GPG key
  ansible.builtin.shell:
    cmd: "curl -fsSL '{{ charm_apt_repo_url }}/gpg.key' | gpg --dearmor -o '{{ apt_keyrings_dir }}/{{ charm_apt_repo_name }}.gpg'"
    creates: "{{ apt_keyrings_dir }}/{{ charm_apt_repo_name }}.gpg"

- name: add charm APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ apt_keyrings_dir }}/{{ charm_apt_repo_name }}.gpg] {{ charm_apt_repo_url }}/ * *"
    state: present
    filename: "{{ charm_apt_repo_name }}"
