---
- name: check if Gum is installed
  ansible.builtin.shell: |
    command -v gum >/dev/null 2>&1
  register: gum_installed
  changed_when: false
  failed_when: false

- name: install Go
  ansible.builtin.shell: |
    if ! command -v /usr/local/go/bin/go >/dev/null 2>&1; then
      curl -L https://go.dev/dl/go1.22.1.linux-armv6l.tar.gz | tar -C /usr/local -xzf -
      echo 'export PATH=$PATH:/usr/local/go/bin' > /etc/profile.d/goenv.sh
    fi
  when: gum_installed.rc != 0

- name: verify Go installation
  ansible.builtin.shell: |
    . /etc/profile
    go version
  when: gum_installed.rc != 0

- name: install Gum
  ansible.builtin.shell: |
    GOBIN=/usr/local/bin GO111MODULE=on /usr/local/go/bin/go install github.com/charmbracelet/gum@v0.13.0
  when: gum_installed.rc != 0
