---
- name: install Go
  import_tasks: install-go.yml

- name: install Gum
  ansible.builtin.shell: |
    command -v gum >/dev/null 2>&1 || GOBIN='{{ go_bin_dir }}' '{{ go_root_dir }}/bin/go' install github.com/charmbracelet/gum@latest
