---
- name: gather os family facts
  ansible.builtin.setup: { gather_subset: [ "!all", "!min", "os_family" ] }

- name: add charm APT repository
  import_tasks: charm-repo.yml
  when: ansible_os_family in ['Debian', 'Ubuntu']

- name: update apt and install gum
  ansible.builtin.apt:
    name: [ gum ]
    update_cache: yes
  when: ansible_os_family in ['Debian', 'Ubuntu']
