---
- name: install avahi
  ansible.builtin.apt:
    name:
      - avahi-daemon
    state: present
  become: true


- name: set defaults
  block:
    - name: set default device_info.machine
      when: device_info.machine is undefined
      block:
        - name: compute device_info.machine
          become: true
          shell: cat /proc/device-tree/model
          register: device_info_machine_result
        - name: set device_info.machine
          set_fact:
            device_info: "{{ device_info | default({}) | combine({'machine': (device_info_machine_result.stdout | replace('\x00', ''))}) }}"


- name: meta
  block:
    - name: set pretty hostname
      shell: hostnamectl --pretty set-hostname "{{ device_info.pretty_hostname }}"
      when: device_info.pretty_hostname is defined
      become: true
      notify: restart avahi

    - name: get pretty hostname
      register: device_info_pretty_hostname_result
      shell: hostnamectl --pretty

    - name: set pretty hostname fact
      set_fact:
        device_info: "{{ device_info | default({}) | combine({'pretty_hostname': device_info_pretty_hostname_result.stdout}) }}"

    - name: set chassis
      shell: hostnamectl set-chassis embedded
      become: true


- name: configure avahi
  community.general.ini_file:
    path: /etc/avahi/avahi-daemon.conf
    no_extra_spaces: true
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { section: server, option: disallow-other-stacks, value: 'no' }
    - { section: publish, option: publish-hinfo, value: 'yes' }
    - { section: publish, option: publish-workstation, value: 'no' }
  become: true
  notify: restart avahi

- name: copy avahi services
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/avahi/services/{{ item | basename | regex_replace('.j2$', '') }}"
    mode: "0644"
    force: true
  with_fileglob: [ templates/*.service.j2 ]
  become: true
  notify: restart avahi
